# Generated by Django 4.2.5 on 2023-09-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
    ]
